name: Generate-Snake

# Ejecutar cada 6 horas y permitir ejecución manual
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# Otorga permisos de escritura para poder hacer push
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generar la animación del "snake"
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: raultejada24
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Mostrar el estado del repositorio para depuración
      - name: Show Git Status
        run: git status

      # Asegurar que la rama "output" existe
      - name: Create output branch if not exists
        run: |
          git fetch origin output || echo "Branch does not exist, creating..."
          git checkout -B output

      # Hacer push de los cambios a la rama "output"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Publicar los archivos en GitHub Pages desde la rama "output"
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
